package ilocGenerator;

/**
 * Created by Jordy van der Zwan on 13-Jun-17.
 *
 * This class is used to generate ILOC code using the parse tree generated by earlier steps.
 * It also uses some more information generated by other steps in the compiler.
 */
public class ILOCGenerator {

}
